### ISSUE TITLE
using sass @import

### ISSUE THREAD

**Issue by ottonascarella** [oklai/koala#248]
Hi there,

First off, thanks for the app!

I'd like to know if there's a way to compile all sass files when you save any of them.

Suppose you have:

/animations.sass
/colours.sass
/header.sass
/body.sass
/style.sass

But the only file you'll actually use on the project is style.css whose content is:

@import animations.sass
@import colours,sass
@import header.sass
@import body.sass

So when you're working on colours.sass, you actually want both colours and style to be compiled on save....

**Comment by marekmaurizio** [comment]
I have a similar problem, but i think it's by design.
I find the current behaviour not optimal. The codekit approach is far better, showing exactly which files get imported and recompiling the whole thing when i save any file. As now, I can't use it with @import and it's good only for small projects.

**Comment by bastiantowers** [comment]
Im using it this way in a similar project and everything is working fine. I'm using Koala on Windows, by the way.

Do you have all the files involved added to your koala project?
In my case, I always configure a new project just dropping the source folder with all the sass files in it, over the Koala UI, and it automatically set up all and every sass file involved appears on the list.
