### ISSUE TITLE
LESS compilation is not working as expected with calc() property

### ISSUE THREAD

**Issue by enworl** [oklai/koala#350]
While adding calc() property

```
width: calc(100% - 40px);
```

Expected resullt should deduct 40px from 100% screensize but compilation makes it width: calc(60%);

**Comment by fvsch** [comment]
That's a Less, problem, not a Koala problem.

Less cannot substract pixels from percentages, since it doesn't know how many pixels is "100%" or how much in percentage is "40px" (this is bound to be different depending on the viewport width in many cases, by the way).

You have two options:
1. Write your styles differently altogether (are you just trying to add 20px margins on each side of an element, for instance?).
2. Use the browser's built-in calc function, in which case you don't want Less to process `calc(100% - 40px)`, you want it to output it as-is.

Browser support for calc: http://caniuse.com/#search=calc
Tell Less to ignore calc: http://stackoverflow.com/questions/16323310/how-can-i-instruct-less-to-ignore-math-for-certain-styles (or use the Strict Math option)
