### ISSUE TITLE
Koala isn't working on Ubuntu 15.04

### ISSUE THREAD

**Issue by duyngha** [oklai/koala#433]
Hi there,
I've upgraded Ubuntu 15.04 version and installed Koala. But when I clicked the Koala icon, then nothing happened. It seem to be the Koala isn't working and I didn't got any error messages. How may I fix this issue?
Regards.

**Comment by QORTEC** [comment]
The reason you cannot launch Koala is because you don't have a dependency.
To my knowledge Ubuntu 15.04 comes with `libudev1` and Koala needs `libudev0`.

To resolve this dependency go to http://packages.ubuntu.com/precise/libudev0 and download the **i386** if you have a **32 bit** system, or **amd64** if you have a **64 bit** system.

I hope this resolves the issue.

**Comment by QORTEC** [comment]
I just noticed there is a section in the FAQ on how to resolve this issue;
https://github.com/oklai/koala/wiki/Unable-to-run-Koala-in-Linux

**Comment by duyngha** [comment]
@QORTEC 
It work!
That's a big help. Thank you so much!

**Comment by schadock** [comment]
Thanks. It works
