### ISSUE TITLE
Compile issue 

### ISSUE THREAD

**Issue by Peripona** [oklai/koala#539]
While compiling my scss file which had a comment at the top 
`/*! normalize.css 2011-08-31T22:02 UTC · http://github.com/necolas/normalize.css */`
The Koala Sass compiler was unable to compile the file and was throwing this error.

```
Error: Invalid US-ASCII character "\xC2"
        on line 1 of /Users/piarasingh/Documents/Tutorials/Practicals/ModularJS/sass/_reset.scss
        from line 5 of /Users/piarasingh/Documents/Tutorials/Practicals/ModularJS/sass/base.scss
  Use --trace for backtrace.
```

**Comment by zaygraveyard** [comment]
@Peripona Does [this](https://github.com/anjlab/bootstrap-rails/issues/66) help?

**Comment by Peripona** [comment]
@zaygraveyard  
I tried this, but no it did not work. 
```
@charset "UTF-8";
/*! normalize.css 2011-08-31T22:02 UTC · http://github.com/necolas/normalize.css */
```
compiler is throwing the same error. 
```
Error: Invalid US-ASCII character "\xC2"
        on line 6 of /Users/piarasingh/Documents/Tutorials/Practicals/ModularJS/sass/base.scss
  Use --trace for backtrace.

```

**Comment by zaygraveyard** [comment]
@Peripona it seams the error is originating from `ModularJS/sass/base.scss`, can you try adding `@charset "UTF-8";` at the beginning of that file?

**Comment by zaygraveyard** [comment]
@Peripona any updates?

**Comment by Peripona** [comment]
Hi Sorry for Late Reply, I checked into this. 
And Voila Yes. 

```
@charset "UTF-8";
/* SASS is the name and earlier there used to be .sass files which didnt require any quotes or ; and wants you to write code in separate lines all the tinme. 
   This has chamge and the latest version as of now 3.22 :: {} and "" and ; are must and does alows greater flexibility. */


/*! normalize.css 2011-08-31T22:02 UTC · http://github.com/necolas/normalize.css */

```

The file is located in my repo [Here ](https://github.com/Peripona/ModularJS)

Thanks Alot.
It Worked.. 👍

**Comment by zaygraveyard** [comment]
Great, I'm glad it worked 😄

**Comment by leotinoco** [comment]
En-->This happens because of errors when writing the code.  Correctly the code would look like this:
Es-->Esto sucede por escribir mal el código. Correctamente el código debe ir así:

`
@charset "UTF-8"

// Google Fonts
@import url('https://fonts.googleapis.com/css?family=Anton|Arimo:400,400i,700,700i|Righteous')

// Variables de fuentes - Font Variables
$titulo: Anton, sans-serif
$texto: Arimo, sans-serif
$fuenteempresa: Righteous, cursive

// Variables de colores - Color Variables
$amarillo: #DAC629
$azul: #001A6E
$rojo: #AC102E
$gris: #555555
$negro: #000000
$blanco: #ffffff

body 
  font: 100% $texto
  color: $negro

`
Without ";" or "{" "}" single or double quotation mark, semicolon or parentheses
Sin ";"," ' ", "{" y "}" comilla simple o doble, punto y coma o paréntesis
