### ISSUE TITLE
最新的版本编译scss出现乱码

### ISSUE THREAD

**Issue by sclovecds** [oklai/koala#596]
之前scss文件中有中文编译的时候就会出现乱码，但是根据网上的步骤找到相应的路径就能解决。
但是新版本，不仅安装的时候不能选着安装目录，并且安装之后，没有了老版本的那种目录，没办法找到scss目录也修改不了，而且打开win7的系统打开的很慢

**Comment by Her-ero** [comment]
2.1.1:
error
_______________________________
E:\...\some.scss
ϵͳ�Ҳ���ָ����·����


2.1.0:
_______________________________
---uncaughtException---
Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.
  at validate (extensions::schemaUtils:34:13)
...


2.0.4 运行正常 (Success)

**Comment by walidream** [comment]
我也遇到了

**Comment by zaygraveyard** [comment]
Are you on windows?

**Comment by zaygraveyard** [comment]
@sclovecds
@oklai used to create the windows installer but now he is unreachable.
And since I don't know how he created them, I had to start from scratch.
I'll try to add the custom installation directory, and probably create an MSI.
As for the slow open on windows, I'm looking into it.
Sorry I didn't understand your before last point, can you clarify.

**Comment by zaygraveyard** [comment]
@Her-ero @walidream see #598

**Comment by walidream** [comment]
我没有遇到 #598,创建后缀名为scss,就会保存
`C:\Users\Administrator\Desktop\aa\a.scss
16:37:32
ϵͳ�Ҳ���ָ����·����`

**Comment by Her-ero** [comment]
@zaygraveyard 
Oh I miss my system info...
Windows 7 SP1, my error looks like #598.
finally, thank you.

**Comment by zaygraveyard** [comment]
@sclovecds Can you try this [v2.1.2](https://github.com/oklai/koala/releases/tag/v2.1.2)?

**Comment by sclovecds** [comment]
@zaygraveyard 
谢谢大神！
现在已经和之前的2.0.4的版本一样了，启动速度也很快了并且安装的gems目录都有了，编译scss 的时候中文出现error的问题也可以在对应的目录上添加相应的代码就可以解决了！
非常感谢大神辛苦解决bug！
