### ISSUE TITLE
Began deleting everything on hard drive

### ISSUE THREAD

**Issue by jonnow** [oklai/koala#638]
**2.2.0**

**Bug report**

Downloaded the latest version and upon installing the app attempted to delete everything on my hard drive starting with VS Code. Luckily I caught it before it got any further. Has website become infected?

**Comment by zaygraveyard** [comment]
I highly doubt it's an infection on our side.
One thing that can explain this is that the installer deletes all the files in the install directory (the destination) before installing the app.
It does that to handle the case when the user is reinstalling Koala (e.g. to update it).

Does this explain what happened with you?

**Comment by jonnow** [comment]
Could well be, yes. Is there anything in the documentation to highlight this?

**Comment by zaygraveyard** [comment]
No but [this](https://github.com/oklai/koala/blob/master/assets-windows/installer.nsi#L34) is the line of the install script that is responsible.

I'll try add a confirmation dialog for when the install dir already exists.

**Comment by zaygraveyard** [comment]
Fixed in [v2.3.0](https://github.com/oklai/koala/releases/tag/v2.3.0)

**Comment by Klipper** [comment]
I try to install latest version of Koala (2.3.0) on my Win 10 laptop. During installation I get an alert that the directory C:\Program Files (x86)\Koala\  already exist, and that the installer will delete all existing files and folders in that directory before installing Koala. 
The very weird thing is that there is no directory 'Koala' on my system at all. When I change name of directory from 'Koala' to i.e. 'KoalaCompiler' I again get the same alert. So I don' t dare to go on, because I'm not sure things get deleted like written her above. Please tell me what's going on? Is it safe to go on with this installer?
![image](https://user-images.githubusercontent.com/3924467/33140216-a1501cde-cfaf-11e7-9b2f-a8ebba5f0f8a.png)
