### ISSUE TITLE
sass native compiler doesn't work properly with css variables

### ISSUE THREAD

**Issue by vergellan** [oklai/koala#731]
**Koala version**
2.3.0
**Bug report or feature request?**
Bug report

I have the css variables in my scss like this:

```
$backgroundColor: #fff;
:root {
  --backgroundColor: $backgroundColor;
  --backgroundTransparentColor: transparentize($backgroundColor, 0.2);
  }
```
But when i compile the file i still get the same 

`:root{--backgroundColor: $backgroundColor;--backgroundTransparentColor: transparentize($backgroundColor, 0.2)}`

**Comment by zaygraveyard** [comment]
It's not a problem with Koala but with the SASS compiler, I tried it on [codepen](https://codepen.io/anon/pen/ZrEegv) and I get the same result!
I don't use SCSS so I don't know if we are doing something wrong 😟

**Comment by vergellan** [comment]
Ok, but i`ve checked in sassmeister.com - sass 3(4) and libsass 3 do it good. Can I use the custom sass compiler with the current ver of Koala? Do I need to install ruby?

**Comment by zaygraveyard** [comment]
I found the culprit, [in v3.5.0 the way CSS variables are handled has changed](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#Backwards_Incompatibilities_--_Must_Read_)

Since in Koala v2.3.0 the Sass compiler has been updated to v3.5.2, you need to do something like:
```
$backgroundColor: #fff;
:root {
  color: $backgroundColor;
  --backgroundColor: #{$backgroundColor};
  --backgroundTransparentColor: #{transparentize($backgroundColor, 0.2)};
 }
```

As for installing a custom Sass compiler, it is possible as long as it has the same CLI (Command Line Interface) and you would have to install ruby too. In the Koala's settings you can specify the path to the sass executable to be used.

**Comment by vergellan** [comment]
Thank you, I`ll try this way.
