### ISSUE TITLE
Autoprefix dont work

### ISSUE THREAD

**Issue by doiftrue** [oklai/koala#757]
**Koala version** 2.3.0

When compiling css to min.css auto-prefixes are not added...

![](https://clip2net.com/clip/m399748/92b28-clip-36kb.png)

![](https://clip2net.com/clip/m399748/501d5-clip-56kb.png)

**Comment by zaygraveyard** [comment]
Prefixes are added (I think) but not for `flex` because of the browser list autoprefix is using.
You change the list in the [project settings](https://github.com/oklai/koala/wiki/Using-project-settings), see the property `autoprefixConfig` example in [koala-config-of-less.json](https://github.com/oklai/koala/blob/develop/src/app/settings/koala-config-of-less.json).

**Comment by doiftrue** [comment]
Found the error - it was an error in source css file... Thanks for the answer!
