### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [oklai/koala#791]
The last commits were ~1 year ago.
Is it planned to continue / work on new versions, are you looking for maintainers or is the development paused?

**Comment by zaygraveyard** [comment]
I hope to work on new versions but currently, I don't have a lot of free time on my hands
Since I don't use Koala anymore (I use command line tools) and the original author has probably abandoned this project, the development kind of stopped (unfortunately) 😓 

But if anyone wants to help maintain Koala I'll be more than welcoming 😄

**Comment by DanielRuf** [comment]
> has probably abandoned this project

Well, we do not know for sure what happend to him or so.
The question is if you and others have enough rights (on GitHub and so on) to create new releases, push to all branches, close issues and PRs, edit the repo settings and so on.

If not it would be better to create an org with teams and create the next version there for easier maintenance with others.

**Comment by zaygraveyard** [comment]
His latest activity online (that I can find) dates from 2017
But the domain koala-app.com's registration has last been updated in December of 2018
So I don't know what's going on

I don't know what I can do, but I know what I tried to do

I'm a collaborator so I can:
* push to all branches
* edit and close issues and PRs
* create new releases
* update the website (which is in a specific branch of this repo)

And can't:
* edit the repo's settings (probably including adding new collaborators)
* manage the domain koala-app.com

> If not it would be better to create an org with teams and create the next version there for easier maintenance with others.

It definitely would be, and I was thinking of creating a fork (kind of) with maybe a different name (since I don't know if we can use the same name) and it would be a complete rewrite that uses [electron](https://electronjs.org/) probably.
And I would probably need some colaborators willing to help since I don't know when I'll have enough time to work on it

All ideas are welcome

**Comment by djibe** [comment]
Hi,
I am trying to build Koala on Windows first,
then I'll try to update its dependencies.

Which NW.JS version should I use ?
Do you have a detailed tutorial to learn this ?

Thanks

**Comment by zaygraveyard** [comment]
The last NW.JS version used was probably v0.26.6
But the latest version of NW.JS should, in theory, work fine

I usually build it on a mac
But I'll try to build it on windows tomorrow and I'll let you know what steps to follow

**Comment by DanielRuf** [comment]
> The last NW.JS version used was probably v0.26.6
> But the latest version of NW.JS should, in theory, work fine
> 
> I usually build it on a mac
> But I'll try to build it on windows tomorrow and I'll let you know what steps to follow

A quick Travis CI setup would be also an idea as they support macOS, Linux and Windows.

**Comment by zaygraveyard** [comment]
@DanielRuf I have never used Travis CI, so I don't really know what it's capable of doing or how to set it up :sweat_smile: 
But I'll look into it when I get the chance

**Comment by oklai** [comment]
Hi guys, I am sorry that I am not paying enough attention to this project.
I think the project has stopped. The development method has changed a lot now, and there are many better alternatives in the open source community.
Next, I will add a stop maintenance statement to the READ.me file.
If someone is still willing to continue maintenance, welcome to create a new project, I agree with this.

Special thanks to @zaygraveyard  for maintaining this project, you are great!

**Comment by djibe** [comment]
Thanks for all your quick answers.
Koala is great app and loved it.
I'll try Scout App then.

**Comment by Thalius** [comment]
I think Koala is a great app, too bad the project stopped. What alternatives do you recommend?

**Comment by DanielRuf** [comment]
https://alternativeto.net/software/koala/ lists some.

**Comment by morrow95** [comment]
Just curious what others have used/tried that is most similar to Koala?  I am going to give prepros a try as it 'looks' similar, but would like to hear what others think.  My only use is minimizing css and js and being able to specify the input/output location... something simple that works behind the scenes as I make changes.

**Comment by DanielRuf** [comment]
Many use CodeKit too (paid).

**Comment by KBischof** [comment]
I used Prepos before Koala. I moved to Koala because it was open-source. I will move back to Prepos, which is 'free' if you don't mind the occasional license prompt. I will miss Koala!
